version: '3.9'
services:

  db:
    container_name: fastapi_clean_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:14-alpine
    networks:
      - network
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: ../dockerfiles/backend/Dockerfile
    container_name: fastapi_clean_backend
    depends_on:
      - db
    environment:
      - DB_HOST=fastapi_clean_db
      - DB_PORT=5432
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    networks:
      - network
      - nginx
    ports:
      - ${ADMIN_PORT}:8080
      - ${BACKEND_PORT}:8000

networks:
  nginx:
    external: true
  network:
    driver: bridge

volumes:
  db_data:
