name: Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Submodule Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Submodule update
        run: |
          git pull --recurse-submodules
          git submodule update --recursive --remote

      - name: Commit update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "(ASS) Auto Submodule Sync" && git push || echo "no changes to commit"
